# Generated by Django 5.1.1 on 2025-02-28 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras.', regex='^[a-zA-Z]+$')])),
            ],
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='frec',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='proteinas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='receta',
            name='tipo_comida',
        ),
        migrations.AddField(
            model_name='receta',
            name='tipo_comida',
            field=models.ManyToManyField(related_name='recetas', to='app.tipocomida'),
        ),
    ]
