# Generated by Django 5.1.1 on 2025-03-04 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingrediente_nombre_alter_receta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras, espacios y vocales con tilde.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras, espacios y vocales con tilde.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ\\s]+$')]),
        ),
    ]
