# Generated by Django 5.1.1 on 2025-03-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_listacompra_listacompraitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listacompraitem',
            unique_together={('lista', 'ingrediente')},
        ),
    ]
