# Generated by Django 5.1.1 on 2025-04-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ingrediente_nombre_alter_receta_nombre_familia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='app.familia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='app.familia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listacompra',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listas_compra', to='app.familia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='app.familia'),
            preserve_default=False,
        ),
    ]
