# Generated by Django 5.1.1 on 2025-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_calendario_familia_alter_ingrediente_familia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='codigo_invitacion',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
