# Generated by Django 5.1.1 on 2025-04-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_familia_administrador_solicituduniónfamilia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendario',
            unique_together={('familia', 'fecha')},
        ),
    ]
