# Generated by Django 5.1.1 on 2025-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_calendario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
