# Generated by Django 5.1.1 on 2025-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_calendario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la receta (opcional).', null=True, verbose_name='Descripción'),
        ),
    ]
