# Generated by Django 5.1.1 on 2025-04-19 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_receta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='carbohidratos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
