# Generated by Django 5.1.1 on 2025-04-19 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_receta_carbohidratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='objetivo_carbohidratos',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
