# Generated by Django 5.1.1 on 2025-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_calendario_objetivo_carbohidratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='combinable',
            field=models.BooleanField(default=True, help_text='Indica si la receta puede combinarse con otras.'),
        ),
    ]
